### ISSUE TITLE
unable to find '<...>/main.import.js(x)'

### ISSUE THREAD

**Issue by dingfengquek** [vazco/universe-modules#38] opened 2015-12-20 02:27 UTC
Unable to find the module when the filename is main.import.js or main.import.jsx.

I'm not sure whether this is replicable in other environments; If it's an issue, it's a minor inconvenience only: documenting it down would solve it (if the code is hard to change).

Please close if it can't be replicated.

**Comment by MacRusher** [comment] 2015-12-21 13:32
How are you loading the module? Inside other `.import.js(x)` file or from normal js file using `System.import('/main')`?
In the second case usual Meteor file loading order is still important, and `main` files are loaded at the end, so the module may not be ready at the time you are requesting it. The same way you cannot `System.import('/z')` inside `a.js`.
We take care of this inside modules so you can do `import z from './z'` inside `a.import.js`, but for other cases Meteor normal rules are still in play.

**Comment by dingfengquek** [comment] 2015-12-24 16:27
I'm doing this inside a .import.js(x) file, on the client.

For e.g., I just tried it again with
- /zzz-module-entrypoint/inside.import.js : This file has two lines:
  - import '/yyy-router/';
  - import '/client/main';
- /client/main : This file has one line:
  - export default { x: 1 };

When I run the app on the client, I get this error:

Uncaught (in promise) [Universe Modules]: Trying to load module "/client/main" that doesn't exist!
    Error loading /_modules_/app/client/main as "/client/main" from /_modules_/app/zzz-module-entrypoint/inside

**Comment by MacRusher** [comment] 2015-12-26 11:50
I'm not able to reproduce it right now.
As a temporary workaround please don't use main as a module name to be imported.
I'll look into it after the holidays.

**Comment by dingfengquek** [comment] 2015-12-26 13:13
Noted. I'll upload a Meteor project tarball where I can consistently produce this error, after the holidays as well.

**Comment by MacRusher** [comment] 2015-12-26 13:14
That would be great, thanks!
26 gru 2015 14:13 "Dingfeng Quek" notifications@github.com napisał(a):

**Comment by dingfengquek** [comment] 2015-12-28 01:15
[universe-modules-bug.tar.gz](https://github.com/vazco/universe-modules/files/72880/universe-modules-bug.tar.gz)

See readme.md

Ran it on OS X 10.10.5, Meteor 1.2.1

Meteor package versions:

autopublish@1.0.4
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.1.0
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
es5-shim@4.1.14
fastclick@1.0.7
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
insecure@1.0.4
jquery@1.11.4
launch-screen@1.0.4
livedata@1.0.15
logging@1.0.8
meteor@1.1.10
meteor-base@1.0.1
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
mongo@1.1.3
mongo-id@1.0.1
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
promise@0.5.1
random@1.0.5
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
session@1.1.1
spacebars@1.0.7
spacebars-compiler@1.0.7
standard-minifiers@1.0.2
templating@1.1.5
templating-tools@1.0.0
tracker@1.0.9
ui@1.0.8
underscore@1.0.4
universe:modules@0.6.7
universe:modules-compiler@1.0.5
url@1.0.5
webapp@1.2.3
webapp-hashing@1.0.5

**Comment by dingfengquek** [comment] 2015-12-28 01:21
[Temporarily removed]

**Comment by dingfengquek** [comment] 2015-12-28 01:27
[universe-modules-bug.tar.gz](https://github.com/vazco/universe-modules/files/72886/universe-modules-bug.tar.gz)

EDIT: Added .meteor directory to the tar (excludes .meteor/local)

**Comment by dingfengquek** [comment] 2016-01-13 19:58
hey, since Meteor 1.3 would have modules, i don't think this issue would be much relevant in the long-term, nor is it that important to verify whether this the coding error leading to this issue will lead to other more critical problems.

immediate needs: anyone who encounters this can just use another filename, until 1.3 is stable.

thanks though!

**Comment by radekmie** [comment] 2019-12-18 13:21
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.

**Closed as completed by radekmie** 2019-12-18 13:21 UTC
Labels: bug
